language: android
dist: trusty
android:
  components:
    - yes | sdkmanager --licenses && yes | sdkmanager --update
    - build-tools-28.0.3
    - android-29
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
    - ./gradlew assembleDebug
    